Speeches = {}

Speeches.male = {}
Speeches.male = {
    ['NO'] = {
        'A_M_M_SALTON_02_WHITE_FULL_01',
        'A_M_O_SALTON_01_WHITE_FULL_01',
        'A_M_Y_BEACHVESP_02_WHITE_FULL_01',
        'A_M_Y_BEACHVESP_01_WHITE_FULL_01',
        'A_M_Y_BEACH_03_BLACK_FULL_01'
    },
    ['CALL_COPS_COMMIT'] = {
        'G_M_Y_LOST_03_WHITE_FULL_01',
        'S_M_Y_AIRWORKER_BLACK_FULL_02',
        'S_M_M_PILOT_01_BLACK_FULL_01',
        'S_M_Y_AMMUCITY_01_WHITE_MINI_01',
        'S_M_Y_BAYWATCH_01_BLACK_FULL_02',
        'S_M_Y_BAYWATCH_01_WHITE_FULL_01',
        'A_F_M_FATWHITE_01_WHITE_MINI_01',
        'A_F_M_SALTON_01_WHITE_MINI_02',
        'A_M_M_SKATER_01_WHITE_MINI_01',
        'A_M_Y_SUNBATHE_01_WHITE_MINI_01',
        'A_M_Y_VINEWOOD_04_WHITE_MINI_01',
        'S_F_M_FEMBARBER_BLACK_MINI_01',
        'MP_M_SHOPKEEP_01_LATINO_MINI_01',
        'S_F_M_SHOP_HIGH_WHITE_MINI_01'
    },
    ['CALL_COPS_THREAT'] = {
        'G_M_Y_LOST_03_WHITE_FULL_01',
        'S_M_Y_AIRWORKER_BLACK_FULL_02',
        'S_M_M_PILOT_01_BLACK_FULL_01',
        'S_M_Y_AMMUCITY_01_WHITE_MINI_01',
        'S_M_Y_BAYWATCH_01_BLACK_FULL_02',
        'S_M_Y_BAYWATCH_01_WHITE_FULL_01',
        'A_F_M_FATWHITE_01_WHITE_MINI_01',
        'A_F_M_SALTON_01_WHITE_MINI_02',
        'A_M_M_SKATER_01_WHITE_MINI_01',
        'A_M_Y_SUNBATHE_01_WHITE_MINI_01',
        'A_M_Y_VINEWOOD_04_WHITE_MINI_01',
        'S_F_M_FEMBARBER_BLACK_MINI_01',
        'MP_M_SHOPKEEP_01_LATINO_MINI_01',
        'S_F_M_SHOP_HIGH_WHITE_MINI_01'
    }
}


Speeches.female = {
    ['NO'] = {
        'A_F_M_BEVHILLS_02_BLACK_FULL_01',
        'A_F_M_BEVHILLS_02_BLACK_FULL_02',
        'A_F_M_BEVHILLS_02_WHITE_FULL_01',
        'A_F_M_BEVHILLS_02_WHITE_FULL_02',
        'A_F_M_SALTON_01_WHITE_FULL_02',
        'A_F_Y_BEACH_BLACK_FULL_01',
        'A_F_Y_BEACH_BLACK_FULL_02',
        'A_F_Y_FITNESS_01_WHITE_FULL_01',
        'A_F_Y_FITNESS_02_BLACK_FULL_01',
        'A_F_Y_HIPSTER_02_WHITE_FULL_01',
        'A_F_Y_TOURIST_01_WHITE_FULL_01'
    },
    ['CALL_COPS_COMMIT'] = {
        'A_F_M_BEVHILLS_02_WHITE_FULL_01',
        'A_F_M_KTOWN_02_KOREAN_FULL_01',
        'A_F_M_SALTON_01_WHITE_FULL_02',
        'A_F_M_SALTON_01_WHITE_FULL_03',
        'A_F_Y_EASTSA_03_LATINO_FULL_01',
        'S_F_M_PONSEN_01_BLACK_01',
        'S_F_Y_AIRHOSTESS_01_BLACK_FULL_01',
        'S_F_Y_AIRHOSTESS_01_WHITE_FULL_01',
        'S_F_Y_AIRHOSTESS_01_WHITE_FULL_02',
        'S_F_Y_BAYWATCH_01_BLACK_FULL_01',
        'S_F_Y_BAYWATCH_01_WHITE_FULL_01'
    },
    ['CALL_COPS_THREAT'] = {
        'A_F_M_BEVHILLS_02_WHITE_FULL_01',
        'A_F_M_KTOWN_02_KOREAN_FULL_01',
        'A_F_M_SALTON_01_WHITE_FULL_02',
        'A_F_M_SALTON_01_WHITE_FULL_03',
        'A_F_Y_EASTSA_03_LATINO_FULL_01',
        'S_F_M_PONSEN_01_BLACK_01',
        'S_F_Y_AIRHOSTESS_01_BLACK_FULL_01',
        'S_F_Y_AIRHOSTESS_01_WHITE_FULL_01',
        'S_F_Y_AIRHOSTESS_01_WHITE_FULL_02',
        'S_F_Y_BAYWATCH_01_BLACK_FULL_01',
        'S_F_Y_BAYWATCH_01_WHITE_FULL_01'
    }
}